eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.3.208:8761/eureka/
      
server:
  port: 8766
  
spring:
  application:
    name: eshop-dataaggr-service
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
    url: jdbc:mysql://192.168.3.205:3306/eshop
    username: root
    password: root
  rabbitmq:
    host: 192.168.3.205
    port: 5672  
    connection-timeout: 600000
    username: rabbitadmin  
    password: 123456
   
    